// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhqlrcpyetzcqnoituxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ocWxyY3B5ZXR6Y3Fub2l0dXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Nzg1NDEsImV4cCI6MjA3MzI1NDU0MX0.u5dcxD0zWA5cUFuejuK7-n4b5qd9u23388k6nwU5tjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});